import React,{useEffect,useState} from 'react';
import { SectionHeader } from '../../components/common/SectionHeader';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { useApp } from '../../context/AppContext';
import { apiFetch,isBackendConfigured,createInvite } from '../../lib/reachApi';

export const SecurityRosterPage:React.FC=()=>{const {staff,institutions,refreshIncidents}=useApp();const current=institutions[0];const [members,setMembers]=useState<any[]>([]);const [userId,setUserId]=useState('');const [type,setType]=useState('staff');const [message,setMessage]=useState('');const [inviteEmail,setInviteEmail]=useState('');const [inviteRole,setInviteRole]=useState<'staff'|'security-desk'>('staff');const [inviteCode,setInviteCode]=useState('');useEffect(()=>{if(isBackendConfigured)void apiFetch<{data:any[]}>('/members').then(r=>setMembers(r.data||[])).catch(()=>undefined);},[]);if(!current)return <div className="reach-card" style={{padding:'2rem'}}><h2>Institution data unavailable</h2></div>;const add=async()=>{if(!userId)return;try{await apiFetch('/responders',{method:'POST',body:JSON.stringify({user_id:userId,responder_type:type})});setMessage('Responder added.');setUserId('');await refreshIncidents();}catch(e){setMessage(e instanceof Error?e.message:'Unable to add responder');}};return <div style={{display:'flex',flexDirection:'column',gap:'2rem'}}><SectionHeader eyebrow={`Institution - ${current.name}`} tag={current.code} title="Security roster" subtitle="Security guards, responders, and shift personnel deployed for this institution."/><div className="reach-card" style={{padding:'1.5rem',gap:'1rem'}}><h2 style={{fontSize:'1.2rem',fontWeight:800}}>Invite staff or security desk</h2><div style={{display:'flex',gap:'.75rem',flexWrap:'wrap'}}><input type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="person@example.com"/><select value={inviteRole} onChange={e=>setInviteRole(e.target.value as any)}><option value="staff">Response staff</option><option value="security-desk">Security desk</option></select><Button variant="primary" disabled={!isBackendConfigured||!inviteEmail} onClick={()=>void createInvite(inviteEmail,inviteRole).then(r=>{setInviteCode(r.code);setMessage('Invite created. Share this one-time code securely.');}).catch(e=>setMessage(e instanceof Error?e.message:'Unable to create invite'))}>Generate invite</Button></div>{inviteCode&&<p style={{fontFamily:'monospace',fontWeight:800}}>Invite code: {inviteCode}</p>}</div>
          <div className="reach-card" style={{padding:'1.5rem',gap:'1rem'}}><h2 style={{fontSize:'1.2rem',fontWeight:800}}>Add responder</h2><div style={{display:'flex',gap:'.75rem',flexWrap:'wrap'}}><select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Select active member</option>{members.filter(m=>m.status==='active'&&m.role!=='institution').map(m=><option key={m.user_id} value={m.user_id}>{m.full_name} · {m.role}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="staff">Response staff</option><option value="security">Security responder</option></select><Button variant="primary" disabled={!isBackendConfigured||!userId} onClick={()=>void add()}>Add</Button></div>{message&&<p style={{color:'var(--reach-text-secondary)',fontWeight:600}}>{message}</p>}</div><div style={{display:'flex',flexDirection:'column',gap:'1rem'}}>{staff.map(member=><div key={member.id} className="reach-card" style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><div><p style={{color:'var(--reach-text-secondary)',fontSize:'.95rem'}}>{member.role}</p><p style={{fontSize:'1.5rem',fontWeight:900}}>{member.name}</p></div><Badge variant={member.status==='On Duty'?'on-duty':member.status==='On Task'?'responding':'danger'}>{member.status}</Badge></div>)}{!staff.length&&<div className="reach-card"><p>No responders are registered yet.</p></div>}</div></div>};
