package com.reach.relay

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Cross-language canonicalisation fidelity. The fixture src/test/resources/cross_cases.json is
 * generated by the TypeScript relay_protocol.ts (canonicalSourceSigned/canonicalRelaySigned) for
 * payloads with slashes, emoji, quotes, backslashes, control chars and floats. The Kotlin node
 * must produce byte-identical canonical strings, or a packet signed by the PWA/TS side would
 * fail the node's fingerprint/signature check (and vice versa).
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [33])
class CrossLanguageCanonicalTest {
    @Test
    fun `kotlin canonical strings match the TypeScript output byte for byte`() {
        val fixture = javaClass.getResourceAsStream("/cross_cases.json")?.readBytes()?.toString(Charsets.UTF_8)
            ?: run { println("SKIP: cross_cases.json resource not present"); return }
        val root = JSONObject(fixture)
        val mismatches = mutableListOf<String>()
        for (name in root.keys()) {
            val entry = root.getJSONObject(name)
            val packet = JSONObject(entry.getString("packetJson"))
            val jsSource = entry.getString("sourceCanonical")
            val jsRelay = entry.getString("relayCanonical")
            val ktSource = DeviceIdentity.canonicalSource(packet)
            val ktRelay = DeviceIdentity.canonicalRelay(JSONObject(packet.toString()).put("relay_device_id", "relaydev"))
            if (ktSource != jsSource) mismatches += "$name source:\n  js=$jsSource\n  kt=$ktSource"
            if (ktRelay != jsRelay) mismatches += "$name relay:\n  js=$jsRelay\n  kt=$ktRelay"
        }
        assertEquals("canonical mismatches:\n" + mismatches.joinToString("\n"), 0, mismatches.size)
    }
}
